name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest  # Uses Windows runner (best for your tool)

    steps:
    - uses: actions/checkout@v4  # Checks out your repository
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run basic tests
      run: |
        python url_checker.py --test http://example.com
        python url_checker.py --test http://malware.testing.google.test/testing/malware/
